/**
 * Discord Comic Poster Service
 * Posts generated comic images to Discord channels
 */

import { Client, TextChannel, AttachmentBuilder, EmbedBuilder } from 'discord.js';

interface PostComicOptions {
  channelId: string;
  imageData: Buffer;
  prNumber: number;
  prTitle: string;
  prAuthor: string;
  prUrl: string;
  imagePath?: string;
}

interface PostComicResult {
  success: boolean;
  messageId?: string;
  error?: string;
}

/**
 * Post a comic to Discord channel
 */
export async function postComicToDiscord(
  client: Client,
  options: PostComicOptions
): Promise<PostComicResult> {
  const { channelId, imageData, prNumber, prTitle, prAuthor, prUrl, imagePath } = options;

  try {
    console.log(`📤 Posting comic to Discord channel ${channelId}`);

    // Fetch the channel
    const channel = await client.channels.fetch(channelId);

    if (!channel) {
      console.error(`❌ Channel ${channelId} not found`);
      return {
        success: false,
        error: `Channel ${channelId} not found`,
      };
    }

    if (!channel.isTextBased() || !(channel instanceof TextChannel)) {
      console.error(`❌ Channel ${channelId} is not a text channel`);
      return {
        success: false,
        error: `Channel ${channelId} is not a text channel`,
      };
    }

    // Create attachment from image data
    const attachment = new AttachmentBuilder(imageData, {
      name: `pr-${prNumber}-comic.png`,
    });

    // Create embed with PR information
    const embed = new EmbedBuilder()
      .setTitle(`🎨 Comic: PR #${prNumber}`)
      .setDescription(prTitle)
      .setColor(0x5865f2) // Discord blurple
      .addFields(
        { name: '👤 Author', value: prAuthor, inline: true },
        { name: '🔗 Pull Request', value: `[View PR](${prUrl})`, inline: true }
      )
      .setImage(`attachment://pr-${prNumber}-comic.png`)
      .setTimestamp()
      .setFooter({ text: 'Generated by Gemini API' });

    // Send the message
    const message = await channel.send({
      embeds: [embed],
      files: [attachment],
    });

    console.log(`✅ Comic posted to Discord (message ID: ${message.id})`);

    return {
      success: true,
      messageId: message.id,
    };
  } catch (error) {
    console.error('❌ Error posting comic to Discord:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Get Discord client instance
 * This assumes the bot is already connected
 */
export function getDiscordClient(): Client | null {
  // In a real implementation, this would access the global client instance
  // For now, we'll return null and handle it in the caller
  return null;
}
