/**
 * ABC to MP3 Converter Tool - Converts ABC notation to high-quality MP3 audio
 *
 * Features:
 * - Converts ABC musical notation to MIDI format using abcjs library
 * - Renders MIDI to realistic piano audio using FluidSynth + SoundFont
 * - Encodes WAV to MP3 using lamejs
 * - Saves MP3 files to database with downloadable URLs
 * - Stores metadata (title, description, ABC notation)
 * - Integrates with existing music tools (generateSheetMusic, abcToMidi)
 */

import { tool } from 'ai';
import { z } from 'zod';
import abcjs from 'abcjs';
import { midiToMp3Buffer } from '../utils/audioConverter.js';
import { saveMp3File } from '@repo/database';

interface Mp3Metadata {
  id: number;
  type: 'mp3';
  title: string;
  description: string;
  abcNotation: string;
  createdAt: string;
  filename: string;
  fileSize: number;
}

/**
 * Convert ABC notation to MP3 and save to database
 */
async function convertAndSaveMp3(
  abcNotation: string,
  title: string,
  description: string,
  abcSheetMusicId?: number
): Promise<Mp3Metadata> {
  // Validate ABC notation has required headers
  if (!abcNotation.includes('X:') || !abcNotation.includes('K:')) {
    throw new Error('Invalid ABC notation: missing required headers (X: and K:)');
  }

  try {
    // Step 1: Parse ABC notation (server-side, no DOM required)
    const parsedTunes = abcjs.parseOnly(abcNotation);

    if (!parsedTunes || parsedTunes.length < 1) {
      throw new Error('Failed to parse ABC notation');
    }

    const firstTune = parsedTunes[0];
    if (!firstTune || !firstTune.lines || firstTune.lines.length < 1) {
      throw new Error('Failed to parse ABC notation - no musical content found');
    }

    console.log('   📝 ABC notation parsed successfully');

    // Step 2: Convert ABC → MIDI using abcjs
    // getMidiFile returns an ARRAY of results (one per tune)
    const midiResult = abcjs.synth.getMidiFile(abcNotation, {
      chordsOff: false,
      program: 0,
      midiOutputType: 'binary', // Returns Uint8Array instead of base64 or HTML
    });

    // Handle array return - take first tune
    const midiBinary = Array.isArray(midiResult) ? midiResult[0] : midiResult;

    if (!(midiBinary instanceof Uint8Array)) {
      throw new Error(`Failed to generate MIDI data: unexpected type ${typeof midiBinary}`);
    }

    // Convert Uint8Array to Node Buffer
    const midiBuffer = Buffer.from(midiBinary);
    console.log(`   🎹 MIDI generated (${midiBuffer.length} bytes)`);

    // Step 3: Convert MIDI → MP3 using FluidSynth + SoundFont + lamejs
    console.log('   🎵 Converting MIDI to MP3 with FluidSynth...');
    const mp3Buffer = await midiToMp3Buffer(midiBuffer);
    console.log(`   ✅ MP3 generated (${mp3Buffer.length} bytes)`);

    // Step 4: Save to database
    const savedRecord = await saveMp3File({
      title,
      description,
      mp3Data: mp3Buffer,
      abcNotation,
      abcSheetMusicId,
      filename: `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.mp3`,
      metadata: {
        type: 'mp3',
        encoding: 'MP3 (128 kbps)',
        source: 'FluidSynth + SoundFont',
      },
    });

    console.log(`   💾 Saved MP3 to database: ${savedRecord.id}`);

    // Return metadata
    const metadata: Mp3Metadata = {
      id: savedRecord.id,
      type: 'mp3',
      title,
      description,
      abcNotation,
      createdAt: new Date(Number(savedRecord.createdAt) * 1000).toISOString(),
      filename: savedRecord.filename,
      fileSize: savedRecord.fileSize || mp3Buffer.length,
    };

    return metadata;
  } catch (error) {
    throw new Error(`MP3 conversion failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

export const abcToMp3Tool = tool({
  description: 'Convert ABC musical notation to high-quality MP3 audio with realistic piano sound. Takes ABC notation (text-based music notation) and generates a professional-quality MP3 file using FluidSynth + SoundFont for authentic piano tones. Perfect for creating playable audio files from sheet music generated by generateSheetMusic.',
  inputSchema: z.object({
    abcNotation: z.string().describe('ABC notation to convert to MP3. Should include all required headers (X:, T:, M:, L:, K:) and note data. Can be obtained from generateSheetMusic tool.'),
    title: z.string().optional().describe('Title for the MP3 file (defaults to extracting from ABC notation T: header)'),
    description: z.string().optional().describe('Description of the MP3 file'),
    abcSheetMusicId: z.number().optional().describe('Optional ID of the ABC sheet music record this MP3 is generated from'),
  }),
  execute: async ({ abcNotation, title, description, abcSheetMusicId }) => {
    try {
      console.log('🎵 ABC to MP3: Converting ABC notation to high-quality MP3 audio...');

      // Extract title from ABC notation if not provided
      let mp3Title = title;
      if (!mp3Title) {
        const titleMatch = abcNotation.match(/^T:\s*(.+)$/m);
        mp3Title = titleMatch ? titleMatch[1].trim() : 'Untitled Composition';
      }

      // Generate description if not provided
      const mp3Description = description || `High-quality MP3 audio generated from ABC notation: ${mp3Title}`;

      console.log(`   🎼 Title: ${mp3Title}`);
      console.log(`   📝 ABC notation length: ${abcNotation.length} chars`);

      // Convert and save
      const metadata = await convertAndSaveMp3(abcNotation, mp3Title, mp3Description, abcSheetMusicId);

      // Get server URL from environment or use default
      const serverUrl = process.env.ARTIFACT_SERVER_URL
        || (process.env.NODE_ENV === 'production' ? 'https://omegaai.dev' : 'http://localhost:3001');
      const downloadUrl = `${serverUrl}/api/mp3/${metadata.id}`;

      console.log(`   ✅ MP3 file created: ${metadata.filename}`);
      console.log(`   🔗 Download URL: ${downloadUrl}`);

      // Build usage instructions
      const usageInstructions = `**🎹 High-Quality MP3 Audio Ready!**

**Download:** ${downloadUrl}

**Audio Details:**
- Format: MP3 (128 kbps)
- Sound: Realistic piano via FluidSynth + SoundFont
- Title: ${mp3Title}
- Created: ${new Date(metadata.createdAt).toLocaleString()}
- Size: ${(metadata.fileSize / 1024).toFixed(1)} KB

**How to Use Your MP3:**

**Music Players:**
- iTunes, Spotify, VLC, Windows Media Player, QuickTime
- Any MP3-compatible device (phone, tablet, computer)

**Digital Audio Workstations (DAWs):**
- GarageBand, FL Studio, Ableton Live, Logic Pro, Pro Tools
- Import for editing, mixing, or sampling

**Creative Projects:**
- Background music for videos, podcasts, presentations
- Ringtones and notification sounds
- Game development soundtracks
- Social media content

**Sharing:**
- Upload to SoundCloud, YouTube, Spotify
- Share via email, messaging apps, cloud storage
- Embed in websites or blogs

**Why MP3 sounds better than MIDI:**
- MIDI files use basic synthesizers (often low-quality)
- This MP3 uses FluidSynth with professional SoundFont samples
- Realistic piano sound, natural dynamics, authentic tone
- Ready to play on any device without special software

—
*Format: MP3 | Generated with FluidSynth + SoundFont | Source: ABC notation*`;

      return {
        success: true,
        id: metadata.id,
        type: 'mp3',
        title: mp3Title,
        description: mp3Description,
        downloadUrl,
        filename: metadata.filename,
        fileSize: metadata.fileSize,
        usageInstructions,
        message: `✅ MP3 file created successfully! Download at: ${downloadUrl}`,
      };
    } catch (error) {
      console.error('❌ Error converting ABC to MP3:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to convert ABC notation to MP3',
      };
    }
  },
});
