/**
 * ABC to MIDI Converter Tool - Converts ABC notation to MIDI files
 *
 * Features:
 * - Converts ABC musical notation to MIDI format using abcjs library
 * - Saves MIDI files to artifacts directory with shareable URLs
 * - Validates ABC notation structure before conversion
 * - Stores metadata (title, description, ABC notation)
 * - Provides detailed usage instructions for MIDI software
 * - Integrates with existing music tools (generateSheetMusic, generateSongLyrics)
 */

import { tool } from 'ai';
import { z } from 'zod';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { randomUUID } from 'crypto';
import { getArtifactsDir } from '@repo/shared';
import abcjs from 'abcjs';

// Artifacts directory - use centralized storage utility
const ARTIFACTS_DIR = getArtifactsDir();

interface MidiArtifactMetadata {
  id: string;
  type: 'midi';
  title: string;
  description: string;
  abcNotation: string;
  createdAt: string;
  filename: string;
}

/**
 * Validate ABC notation structure
 */
function validateABCNotation(abcNotation: string): { valid: boolean; error?: string } {
  // Check for required headers
  if (!abcNotation.includes('X:')) {
    return { valid: false, error: 'Missing required header X: (reference number)' };
  }
  if (!abcNotation.includes('K:')) {
    return { valid: false, error: 'Missing required header K: (key signature)' };
  }

  // Basic structure validation
  const lines = abcNotation.trim().split('\n');
  if (lines.length < 2) {
    return { valid: false, error: 'ABC notation too short - must contain headers and music' };
  }

  return { valid: true };
}

/**
 * Convert ABC notation to MIDI using abcjs
 */
function convertABCToMidi(abcNotation: string): Buffer {
  try {
    // Use abcjs to convert ABC to MIDI
    // The synth.getMidiFile function returns a MIDI file as a string that needs to be converted to buffer
    const midiData = abcjs.synth.getMidiFile(abcNotation, {
      chordsOff: false,
      program: 0, // Piano
    });

    // Convert MIDI data to Buffer
    // abcjs returns MIDI as a string, we need to convert it properly
    if (typeof midiData === 'string') {
      // MIDI data is returned as a string, convert to buffer
      const buffer = Buffer.from(midiData, 'binary');
      return buffer;
    } else if (Buffer.isBuffer(midiData)) {
      return midiData;
    } else if (Array.isArray(midiData)) {
      return Buffer.from(midiData);
    }

    throw new Error('Unexpected MIDI data format from abcjs');
  } catch (error) {
    throw new Error(`Failed to convert ABC to MIDI: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

export const abcToMidiTool = tool({
  description: 'Convert ABC musical notation to MIDI format and save as downloadable artifact. Takes ABC notation (text-based music notation) and generates a MIDI file that can be played in music software, DAWs, or web browsers. Perfect for creating playable music from ABC notation generated by generateSheetMusic tool or from user-provided ABC notation. Returns a shareable URL to download the MIDI file.',
  inputSchema: z.object({
    abcNotation: z.string().describe('ABC musical notation to convert to MIDI. Must include required headers (X:, K:) and musical content. Can be obtained from generateSheetMusic tool or provided directly.'),
    title: z.string().optional().describe('Title for the MIDI file (default: extracted from ABC notation T: header or "ABC MIDI")'),
    description: z.string().optional().describe('Description of the music (default: "Converted from ABC notation")'),
  }),
  execute: async ({ abcNotation, title, description }) => {
    try {
      console.log('🎵 ABC to MIDI: Converting ABC notation to MIDI...');

      // Validate ABC notation
      const validation = validateABCNotation(abcNotation);
      if (!validation.valid) {
        console.error(`   ❌ Invalid ABC notation: ${validation.error}`);
        return {
          success: false,
          error: `Invalid ABC notation: ${validation.error}`,
        };
      }

      console.log('   ✅ ABC notation validated');

      // Extract title from ABC notation if not provided
      let midiTitle = title;
      if (!midiTitle) {
        const titleMatch = abcNotation.match(/^T:\s*(.+)$/m);
        midiTitle = titleMatch ? titleMatch[1].trim() : 'ABC MIDI';
      }

      console.log(`   🎼 Converting: "${midiTitle}"`);

      // Convert ABC to MIDI
      let midiBuffer: Buffer;
      try {
        midiBuffer = convertABCToMidi(abcNotation);
        console.log(`   ✅ MIDI generated (${midiBuffer.length} bytes)`);
      } catch (error) {
        console.error('   ❌ Conversion failed:', error);
        return {
          success: false,
          error: error instanceof Error ? error.message : 'Failed to convert ABC to MIDI',
        };
      }

      // Generate unique ID for the artifact
      const id = randomUUID();
      const filename = `${id}.mid`;
      const metadataFilename = `${id}.json`;

      // Create metadata
      const metadata: MidiArtifactMetadata = {
        id,
        type: 'midi',
        title: midiTitle,
        description: description || 'Converted from ABC notation',
        abcNotation,
        createdAt: new Date().toISOString(),
        filename,
      };

      // Save MIDI file
      const midiPath = join(ARTIFACTS_DIR, filename);
      writeFileSync(midiPath, midiBuffer);
      console.log(`   💾 Saved MIDI: ${midiPath}`);

      // Save metadata
      const metadataPath = join(ARTIFACTS_DIR, metadataFilename);
      writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
      console.log(`   💾 Saved metadata: ${metadataPath}`);

      // Generate preview/download URL
      const serverUrl = process.env.ARTIFACT_SERVER_URL
        || (process.env.NODE_ENV === 'production' ? 'https://omegaai.dev' : 'http://localhost:3001');
      const downloadUrl = `${serverUrl}/artifacts/${id}`;

      console.log(`   🔗 Download URL: ${downloadUrl}`);

      // Build usage instructions
      const usageInstructions = `**How to Use This MIDI File:**

1. **Download**: Click the link below to download the MIDI file
2. **Play in Music Software**:
   - DAWs: GarageBand, FL Studio, Ableton Live, Logic Pro, Cubase
   - Notation Software: MuseScore, Finale, Sibelius
   - MIDI Players: Windows Media Player, VLC, QuickTime
   - Web Browsers: Many browsers can play MIDI files directly

3. **Edit & Customize**:
   - Import into any MIDI-compatible software to edit notes, instruments, tempo
   - Change instruments by adjusting MIDI program numbers
   - Add additional tracks and layers

4. **Convert to Audio**:
   - Use a DAW to render MIDI to MP3/WAV
   - Online converters: zamzar.com, cloudconvert.com

**Download**: [${midiTitle}.mid](${downloadUrl})`;

      return {
        success: true,
        id,
        title: midiTitle,
        description: metadata.description,
        downloadUrl,
        filename,
        midiSize: midiBuffer.length,
        abcNotationUsed: abcNotation,
        usageInstructions,
        formattedOutput: `**🎹 MIDI File Generated: ${midiTitle}**

${metadata.description}

**Download**: [${midiTitle}.mid](${downloadUrl})

**File Details**:
- Format: MIDI (.mid)
- Size: ${(midiBuffer.length / 1024).toFixed(2)} KB
- Source: ABC Notation

${usageInstructions}

—
*Converted using abcjs | Artifact ID: ${id}*`,
      };
    } catch (error) {
      console.error('Error converting ABC to MIDI:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to convert ABC to MIDI',
      };
    }
  },
});
