/**
 * ABC to MIDI Converter Tool - Converts ABC notation to MIDI files
 * Uses the abcjs library to generate MIDI from ABC musical notation
 * and saves it as an artifact with a shareable URL.
 */

import { tool } from 'ai';
import { z } from 'zod';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { randomUUID } from 'crypto';
import { getArtifactsDir } from '@repo/shared';
import * as abcjs from 'abcjs';

// Artifacts directory - use centralized storage utility
const ARTIFACTS_DIR = getArtifactsDir();

interface MidiArtifactMetadata {
  id: string;
  type: 'midi';
  title: string;
  description: string;
  abcNotation: string;
  createdAt: string;
  filename: string;
}

/**
 * Validate ABC notation structure
 */
function validateABCNotation(abcNotation: string): { valid: boolean; error?: string } {
  // Basic validation - ABC notation should have required headers
  const hasReferenceNumber = /X:\s*\d+/.test(abcNotation);
  const hasKey = /K:\s*[A-G]/.test(abcNotation);

  if (!hasReferenceNumber) {
    return { valid: false, error: 'ABC notation must include a reference number (X: 1)' };
  }

  if (!hasKey) {
    return { valid: false, error: 'ABC notation must include a key signature (K: C, K: Am, etc.)' };
  }

  return { valid: true };
}

/**
 * Convert ABC notation to MIDI buffer using abcjs
 */
function convertABCToMIDI(abcNotation: string): Buffer {
  try {
    // Use abcjs to generate MIDI from ABC notation
    // abcjs.synth.getMidiFile returns a binary MIDI file as a string
    const midiData = abcjs.synth.getMidiFile(abcNotation, {
      chordsOff: false,
      program: 0, // Piano (MIDI program 0)
    });

    // Convert the MIDI string data to a Buffer
    // The midiData is a binary string that needs to be converted to Buffer
    const midiBuffer = Buffer.from(midiData, 'binary');

    return midiBuffer;
  } catch (error) {
    throw new Error(`Failed to convert ABC to MIDI: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Save MIDI artifact to filesystem
 */
function saveMidiArtifact(
  midiBuffer: Buffer,
  title: string,
  description: string,
  abcNotation: string
): MidiArtifactMetadata {
  const id = randomUUID();
  const filename = `${id}.mid`;
  const filepath = join(ARTIFACTS_DIR, filename);

  // Save the MIDI file
  writeFileSync(filepath, midiBuffer);

  // Save metadata
  const metadata: MidiArtifactMetadata = {
    id,
    type: 'midi',
    title,
    description,
    abcNotation,
    createdAt: new Date().toISOString(),
    filename,
  };

  const metadataPath = join(ARTIFACTS_DIR, `${id}.json`);
  writeFileSync(metadataPath, JSON.stringify(metadata, null, 2), 'utf-8');

  return metadata;
}

export const abcToMidiTool = tool({
  description: `Convert ABC musical notation to MIDI format and save as a downloadable artifact.

  ABC notation is a text-based format for music notation. This tool converts it to MIDI (Musical Instrument Digital Interface) format,
  which can be played in music software, DAWs, notation software, and web browsers.

  Perfect for:
  - Converting sheet music (generated by generateSheetMusic tool) to playable audio
  - Creating MIDI files for music production workflows
  - Generating music that can be imported into DAWs (GarageBand, FL Studio, Ableton, Logic Pro)
  - Producing files for music notation software (MuseScore, Finale, Sibelius)
  - Making music accessible to MIDI players and devices

  The generated MIDI file will be saved with a shareable URL that users can download and use in their music software.`,

  inputSchema: z.object({
    abcNotation: z.string().describe('ABC musical notation to convert to MIDI. Must be valid ABC notation with required headers (X: reference number, K: key signature) and properly formatted music notation.'),
    title: z.string().optional().describe('Title for the MIDI file (defaults to extracting from ABC notation or "Untitled")'),
    description: z.string().optional().describe('Brief description of the music (defaults to "MIDI file generated from ABC notation")'),
  }),

  execute: async ({ abcNotation, title, description }) => {
    try {
      console.log('🎵 ABC to MIDI: Converting ABC notation to MIDI...');

      // Validate ABC notation
      const validation = validateABCNotation(abcNotation);
      if (!validation.valid) {
        return {
          success: false,
          error: validation.error,
        };
      }

      // Extract title from ABC notation if not provided
      let finalTitle = title;
      if (!finalTitle) {
        const titleMatch = abcNotation.match(/T:\s*(.+)/);
        finalTitle = titleMatch ? titleMatch[1].trim() : 'Untitled';
      }

      // Use default description if not provided
      const finalDescription = description || 'MIDI file generated from ABC notation';

      console.log(`   🎼 Title: ${finalTitle}`);
      console.log(`   📝 Converting...`);

      // Convert ABC to MIDI
      const midiBuffer = convertABCToMIDI(abcNotation);

      console.log(`   ✅ Conversion successful (${midiBuffer.length} bytes)`);

      // Save as artifact
      const metadata = saveMidiArtifact(midiBuffer, finalTitle, finalDescription, abcNotation);

      // Get server URL from environment
      const serverUrl = process.env.ARTIFACT_SERVER_URL
        || (process.env.NODE_ENV === 'production' ? 'https://omegaai.dev' : 'http://localhost:3001');
      const downloadUrl = `${serverUrl}/artifacts/${metadata.id}`;

      console.log(`   🔗 Download URL: ${downloadUrl}`);

      // Build formatted output with usage instructions
      const formattedOutput = `**${finalTitle}** 🎵

MIDI file successfully generated from ABC notation!

**Download:** [${metadata.filename}](${downloadUrl})

**Description:** ${finalDescription}

**File Info:**
- Format: MIDI (.mid)
- Size: ${midiBuffer.length} bytes
- Created: ${new Date(metadata.createdAt).toLocaleString()}

**How to Use This MIDI File:**

📱 **Digital Audio Workstations (DAWs):**
- GarageBand, FL Studio, Ableton Live, Logic Pro, Pro Tools
- Import the MIDI file to edit, arrange, and produce music

🎼 **Music Notation Software:**
- MuseScore, Finale, Sibelius, Dorico
- Open the MIDI file to view and edit sheet music

🎹 **MIDI Players:**
- Windows Media Player, VLC Media Player, QuickTime
- Many web browsers can play MIDI files directly

🎸 **Online Tools:**
- MIDI players and editors available in web browsers
- Convert to other formats (MP3, WAV) using online converters

**Original ABC Notation:**
\`\`\`abc
${abcNotation}
\`\`\`

—
*Generated with [Omega](https://omegaai.dev) | MIDI Format | ${new Date(metadata.createdAt).toLocaleDateString()}*`;

      return {
        success: true,
        midiId: metadata.id,
        title: finalTitle,
        description: finalDescription,
        downloadUrl,
        filename: metadata.filename,
        fileSize: midiBuffer.length,
        createdAt: metadata.createdAt,
        formattedOutput,
        message: `MIDI file created! Download it at: ${downloadUrl}`,
      };
    } catch (error) {
      console.error('❌ Error converting ABC to MIDI:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to convert ABC notation to MIDI',
      };
    }
  },
});
