/**
 * Generate User Image Tool - AI-powered image generation service
 *
 * Features:
 * - Generates images from text prompts using Google's Gemini API
 * - Creates high-quality AI-generated images
 * - Returns image URLs that can be posted directly to Discord
 * - Supports various styles and creative directions
 * - Uses the same model as GeminiComicService for consistency
 */

import { tool } from 'ai';
import { z } from 'zod';
import { GoogleGenerativeAI } from '@google/generative-ai';
import fs from 'fs/promises';
import path from 'path';

/**
 * Generate an image using Google's Gemini API
 * Uses the same model as GeminiComicService for consistency
 */
async function generateImage(
  prompt: string
): Promise<{
  imageUrl: string;
  revisedPrompt?: string;
}> {
  try {
    // Validate API key
    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY environment variable is not set');
    }

    // Initialize Gemini API client
    const genai = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

    // Use the same model as GeminiComicService
    const model = genai.getGenerativeModel({
      model: 'gemini-3-pro-image-preview',
    });

    const result = await model.generateContent(prompt);

    // Extract image data from response
    const response = await result.response;

    if (!response.candidates || response.candidates.length === 0) {
      console.error('❌ No candidates in Gemini response');
      console.error('Response:', JSON.stringify(response, null, 2));
      throw new Error('No image generated by Gemini API');
    }

    const candidate = response.candidates[0];
    if (!candidate.content?.parts) {
      console.error('❌ No content parts in candidate');
      console.error('Candidate:', JSON.stringify(candidate, null, 2));
      throw new Error('Invalid response structure from Gemini API');
    }

    // Find the image part in the response
    let imageData: Buffer | undefined;
    for (const part of candidate.content.parts) {
      // Check for inline data (base64 encoded image)
      if ((part as any).inlineData?.mimeType?.startsWith('image/')) {
        const base64Data = (part as any).inlineData.data;
        imageData = Buffer.from(base64Data, 'base64');
        console.log(`✅ Extracted image (${imageData.length} bytes, ${(part as any).inlineData.mimeType})`);
        break;
      }
    }

    if (!imageData) {
      console.error('❌ No image data found in response');
      console.error('Parts:', JSON.stringify(candidate.content.parts, null, 2));
      throw new Error('No image data in Gemini response');
    }

    // Save the image to file system
    const outputDir = path.join(process.cwd(), 'apps/bot/public/user-images');
    await fs.mkdir(outputDir, { recursive: true });

    const filename = `user-image-${Date.now()}.png`;
    const imagePath = path.join(outputDir, filename);

    await fs.writeFile(imagePath, imageData);
    console.log(`✅ Image saved to: ${imagePath}`);

    // Return URL that can be served via the public endpoint
    const imageUrl = `${process.env.OMEGA_API_URL || 'https://omegaai.dev'}/user-images/${filename}`;

    return {
      imageUrl,
      revisedPrompt: prompt, // Gemini doesn't provide a revised prompt like DALL-E
    };
  } catch (error) {
    console.error('❌ Error generating image:');
    console.error(`   Error Type: ${error instanceof Error ? error.constructor.name : typeof error}`);
    console.error(`   Error Message:`, error instanceof Error ? error.message : String(error));
    console.error(`   Full Error Object:`, JSON.stringify(error, Object.getOwnPropertyNames(error), 2));
    if (error instanceof Error && error.stack) {
      console.error(`   Stack Trace:`, error.stack);
    }
    throw new Error(`Failed to generate image: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

export const generateUserImageTool = tool({
  description: 'Generate AI-powered images from text prompts using Google Gemini API. Creates high-quality, creative images based on user descriptions. Perfect for creating artwork, illustrations, visual concepts, and creative content. Uses the same model as GeminiComicService for consistency and improved safety. The generated images are automatically available as URLs that can be displayed in Discord.',
  inputSchema: z.object({
    prompt: z.string().describe('The text description of the image to generate. Be detailed and specific for best results. Example: "A serene mountain landscape at sunset with snow-capped peaks reflecting in a crystal-clear lake"'),
  }),
  execute: async ({ prompt }) => {
    try {
      console.log('🎨 Generate User Image: Processing image generation...');
      console.log(`   📝 Prompt: ${prompt}`);
      console.log(`   🤖 Model: gemini-3-pro-image-preview (same as GeminiComicService)`);

      const result = await generateImage(prompt);

      console.log(`   ✅ Image generated successfully`);
      console.log(`   🔗 URL: ${result.imageUrl}`);

      return {
        imageUrl: result.imageUrl,
        prompt: prompt,
        success: true,
        message: `Image generated successfully! You can view it at: ${result.imageUrl}`,
      };
    } catch (error) {
      console.error('❌ Error in generateUserImage tool:');
      console.error(`   Error Type: ${error instanceof Error ? error.constructor.name : typeof error}`);
      console.error(`   Error Message:`, error instanceof Error ? error.message : String(error));
      console.error(`   Full Error Object:`, JSON.stringify(error, Object.getOwnPropertyNames(error), 2));
      if (error instanceof Error && error.stack) {
        console.error(`   Stack Trace:`, error.stack);
      }
      return {
        error: error instanceof Error ? error.message : 'Failed to generate image',
        success: false,
        message: 'Failed to generate image. Please try again with a different prompt.',
      };
    }
  },
});
