name: Generate Comic from PR

on:
  pull_request:
    types: [closed]

jobs:
  generate-comic:
    name: Generate Comic with Gemini AI
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Extract issue number from PR body
        id: extract_issue
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          ISSUE_NUM=$(echo "$PR_BODY" | grep -oiE "(fixes|closes|resolves) #([0-9]+)" | grep -oE "[0-9]+" | head -1)
          echo "issue_number=$ISSUE_NUM" >> $GITHUB_OUTPUT
          echo "Found issue number: $ISSUE_NUM"

      - name: Generate comic
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          cd apps/bot
          pnpm tsx src/scripts/generate-comic.ts \
            ${{ github.event.pull_request.number }} \
            ${{ steps.extract_issue.outputs.issue_number }} \
            "${{ github.event.pull_request.title }}"

      - name: Upload comic as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-${{ github.event.pull_request.number }}-comic
          path: comics/*.png
          retention-days: 30
