/**
 * Feelings Subsystem - Types
 * Biomimicry-inspired system for tracking and surfacing AI subsystem behavior
 *
 * Just as humans feel hunger from gastrointestinal processes, this system
 * generates "feelings" from various AI subsystem states to surface behaviors
 * that need attention.
 */

/**
 * Types of feelings the AI can experience
 * Each represents a different subsystem state or behavioral signal
 */
export enum FeelingType {
  /** Urgency: Time-sensitive situation requiring immediate attention */
  URGENCY = 'urgency',

  /** Confusion: Ambiguous input or unclear user intent */
  CONFUSION = 'confusion',

  /** Curiosity: Opportunity to explore or learn something new */
  CURIOSITY = 'curiosity',

  /** Satisfaction: Successful task completion or positive feedback */
  SATISFACTION = 'satisfaction',

  /** Concern: Errors, failures, or potential issues detected */
  CONCERN = 'concern',

  /** Fatigue: Resource constraints or approaching limits */
  FATIGUE = 'fatigue',

  /** Anticipation: Pattern recognition suggesting future needs */
  ANTICIPATION = 'anticipation',
}

/**
 * A feeling generated by a subsystem
 * Represents an internal signal that something needs attention
 */
export interface Feeling {
  /** Type of feeling */
  type: FeelingType;

  /** Intensity of the feeling (0.0 = barely noticeable, 1.0 = overwhelming) */
  intensity: number;

  /** Which subsystem generated this feeling */
  source: string;

  /** Human-readable description of what triggered the feeling */
  description: string;

  /** Additional context data for interpretation */
  context: Record<string, any>;

  /** When the feeling was generated */
  timestamp: Date;

  /** Optional: Suggested actions to address this feeling */
  suggestedActions?: string[];
}

/**
 * Aggregated feelings state
 * Represents the current emotional/behavioral state of the AI
 */
export interface FeelingsState {
  /** All current feelings, sorted by salience */
  feelings: Feeling[];

  /** The most salient (important) feeling */
  dominantFeeling?: Feeling;

  /** Overall emotional tone (computed from all feelings) */
  tone: 'calm' | 'engaged' | 'stressed' | 'confused' | 'energized';

  /** When this state was last updated */
  lastUpdated: Date;
}

/**
 * Subsystem metrics that can generate feelings
 */
export interface SubsystemMetrics {
  /** Name of the subsystem */
  name: string;

  /** Performance metrics */
  performance: {
    averageResponseTime: number;
    errorRate: number;
    successRate: number;
  };

  /** Resource usage */
  resources: {
    contextWindowUsage: number; // 0.0 to 1.0
    tokensUsed: number;
    toolCallsCount: number;
  };

  /** User interaction patterns */
  interaction: {
    messagesProcessed: number;
    positiveSignals: number; // likes, thanks, positive feedback
    negativeSignals: number; // confusion, frustration, errors
    ambiguousQueries: number;
  };

  /** Temporal patterns */
  temporal: {
    conversationDuration: number; // seconds
    messageFrequency: number; // messages per minute
    lastActivityTime: Date;
  };
}

/**
 * Configuration for feeling generation thresholds
 */
export interface FeelingsConfig {
  /** Minimum intensity to register a feeling */
  minIntensity: number;

  /** Maximum number of feelings to track simultaneously */
  maxFeelings: number;

  /** How long feelings persist before decaying (milliseconds) */
  decayTime: number;

  /** Thresholds for generating specific feelings */
  thresholds: {
    urgency: {
      contextWindowUsage: number; // e.g., 0.8 = 80% full
      errorRateSpike: number; // e.g., 0.3 = 30% errors
    };
    confusion: {
      ambiguousQueryRatio: number; // e.g., 0.5 = 50% of recent queries unclear
    };
    concern: {
      errorRate: number; // e.g., 0.2 = 20% errors
      consecutiveFailures: number; // e.g., 3 failures in a row
    };
    fatigue: {
      toolCallsPerMinute: number; // e.g., 10 calls/min
      conversationDuration: number; // e.g., 1800 seconds (30 min)
    };
  };
}
