name: Install with Lockfile Auto-Fix
description: Installs dependencies and auto-fixes lockfile issues on PRs

inputs:
  frozen-lockfile:
    description: Use frozen lockfile mode
    required: false
    default: 'true'
  commit-lockfile-fixes:
    description: Commit lockfile fixes (only for PRs)
    required: false
    default: 'false'
  pr-branch:
    description: PR branch name (required if commit-lockfile-fixes is true)
    required: false
    default: ''

outputs:
  lockfile-fixed:
    description: Whether lockfile was fixed (true/false)
    value: ${{ steps.install.outputs.lockfile_fixed }}

runs:
  using: composite
  steps:
    - name: Install dependencies with lockfile auto-fix
      id: install
      shell: bash
      run: |
        echo "::group::Installing dependencies"
        echo "â„¹ï¸ Attempting install with frozen lockfile..."

        if pnpm install --frozen-lockfile 2>&1 | tee install-output.txt; then
          echo "âœ… Lockfile is in sync"
          echo "lockfile_fixed=false" >> $GITHUB_OUTPUT
        else
          echo "::warning::Lockfile out of sync, regenerating..."
          echo "lockfile_fixed=true" >> $GITHUB_OUTPUT

          # Regenerate lockfile
          pnpm install --no-frozen-lockfile

          # Only commit if requested and we have a branch
          if [ "${{ inputs.commit-lockfile-fixes }}" == "true" ] && [ -n "${{ inputs.pr-branch }}" ]; then
            if git diff --quiet pnpm-lock.yaml; then
              echo "â„¹ï¸ No lockfile changes needed after all"
              echo "lockfile_fixed=false" >> $GITHUB_OUTPUT
            else
              echo "âœ… Lockfile regenerated successfully"

              # Commit and push the updated lockfile
              git add pnpm-lock.yaml
              git commit -m "chore: auto-fix pnpm lockfile" -m "Lockfile was out of sync with package.json changes." -m "Auto-fixed by CI workflow." -m "ðŸ¤– Generated by GitHub Actions"
              git push origin HEAD:${{ inputs.pr-branch }}
              echo "::notice::Lockfile committed and pushed to ${{ inputs.pr-branch }}"
            fi
          fi
        fi
        echo "::endgroup::"
