/**
 * Tests for markdown formatter
 */

import { describe, it, expect } from 'vitest';
import { specToMarkdown } from '../src/core/markdown.js';
import type { TechnicalSpec } from '../src/types/index.js';

describe('specToMarkdown', () => {
  const mockSpec: TechnicalSpec = {
    summary: {
      title: 'Todo List Application',
      overview: 'A simple task management application',
      objectives: ['Build MVP', 'Deploy to production'],
      scope: 'Web application only',
    },
    assumptions: {
      assumptions: ['Users have modern browsers'],
      constraints: ['Budget: $5k'],
      dependencies: ['Auth0 for authentication'],
    },
    requirements: {
      functional: [
        {
          id: 'FR-001',
          description: 'Users can create tasks',
          priority: 'must',
        },
        {
          id: 'FR-002',
          description: 'Users can mark tasks complete',
          priority: 'must',
        },
      ],
      nonFunctional: [
        {
          category: 'performance',
          requirement: 'Page load time',
          metric: '< 2 seconds',
        },
      ],
    },
    testing: {
      strategy: 'Test pyramid with emphasis on unit tests',
      testTypes: [
        {
          type: 'unit',
          coverage: '80%',
          tools: ['vitest'],
        },
        {
          type: 'e2e',
          tools: ['playwright'],
        },
      ],
      acceptanceCriteria: ['All tests pass', 'Coverage > 80%'],
    },
    risks: {
      risks: [
        {
          risk: 'Third-party auth downtime',
          impact: 'high',
          probability: 'low',
          mitigation: 'Implement fallback authentication',
        },
      ],
    },
    milestones: {
      phases: [
        {
          name: 'MVP Development',
          deliverables: ['Basic CRUD operations', 'User authentication'],
        },
        {
          name: 'Production Launch',
          deliverables: ['Deploy to production', 'Monitor metrics'],
          dependencies: ['MVP Development'],
        },
      ],
    },
    metadata: {
      generatedAt: '2024-01-01T00:00:00.000Z',
      depth: 'standard',
      style: 'startup',
      domain: 'web',
    },
  };

  it('should generate valid markdown', () => {
    const markdown = specToMarkdown(mockSpec);

    expect(markdown).toBeDefined();
    expect(markdown.length).toBeGreaterThan(0);
    expect(markdown).toContain('# Todo List Application');
  });

  it('should include all major sections', () => {
    const markdown = specToMarkdown(mockSpec);

    expect(markdown).toContain('## Summary');
    expect(markdown).toContain('## Assumptions & Constraints');
    expect(markdown).toContain('## Requirements');
    expect(markdown).toContain('## Testing & QA');
    expect(markdown).toContain('## Risks & Mitigation');
    expect(markdown).toContain('## Milestones');
  });

  it('should format requirements correctly', () => {
    const markdown = specToMarkdown(mockSpec);

    expect(markdown).toContain('**FR-001**: Users can create tasks *(Priority: must)*');
    expect(markdown).toContain('**FR-002**: Users can mark tasks complete *(Priority: must)*');
  });

  it('should format tables correctly', () => {
    const markdown = specToMarkdown(mockSpec);

    // Risks table
    expect(markdown).toContain('| Risk | Impact | Probability | Mitigation |');
    expect(markdown).toContain('|------|--------|-------------|------------|');
  });

  it('should include metadata footer', () => {
    const markdown = specToMarkdown(mockSpec);

    expect(markdown).toContain('*Generated by Tech Translation Tool*');
    expect(markdown).toContain('**Depth**: standard');
    expect(markdown).toContain('**Style**: startup');
    expect(markdown).toContain('**Domain**: web');
  });

  it('should handle optional sections', () => {
    const minimalSpec: TechnicalSpec = {
      ...mockSpec,
      api: undefined,
      dataModel: undefined,
      devops: undefined,
      security: undefined,
    };

    const markdown = specToMarkdown(minimalSpec);

    expect(markdown).toBeDefined();
    expect(markdown).not.toContain('## API & Interfaces');
    expect(markdown).not.toContain('## Data Model');
    expect(markdown).not.toContain('## DevOps & Infrastructure');
    expect(markdown).not.toContain('## Security & Privacy');
  });

  it('should format API endpoints when present', () => {
    const specWithAPI: TechnicalSpec = {
      ...mockSpec,
      api: {
        endpoints: [
          {
            method: 'GET',
            path: '/api/tasks',
            description: 'Get all tasks',
            response: 'Array of task objects',
          },
          {
            method: 'POST',
            path: '/api/tasks',
            description: 'Create a task',
            parameters: { title: 'string', description: 'string' },
            response: 'Created task object',
          },
        ],
      },
    };

    const markdown = specToMarkdown(specWithAPI);

    expect(markdown).toContain('## API & Interfaces');
    expect(markdown).toContain('**`GET /api/tasks`**');
    expect(markdown).toContain('**`POST /api/tasks`**');
  });

  it('should format data model when present', () => {
    const specWithDataModel: TechnicalSpec = {
      ...mockSpec,
      dataModel: {
        entities: [
          {
            name: 'Task',
            description: 'A user task',
            fields: [
              { name: 'id', type: 'UUID', required: true, description: 'Unique identifier' },
              { name: 'title', type: 'string', required: true, description: 'Task title' },
              { name: 'completed', type: 'boolean', required: true },
            ],
            relationships: ['User'],
          },
        ],
        storage: {
          type: 'PostgreSQL',
          rationale: 'Relational data with ACID guarantees',
        },
      },
    };

    const markdown = specToMarkdown(specWithDataModel);

    expect(markdown).toContain('## Data Model');
    expect(markdown).toContain('### Task');
    expect(markdown).toContain('| Field | Type | Required | Description |');
    expect(markdown).toContain('| id | UUID | Yes | Unique identifier |');
    expect(markdown).toContain('**Type**: PostgreSQL');
  });
});
