/**
 * Evolution Actor
 * Executes approved proposals by creating branches and PRs
 */

import type { ActionResult, EvolutionProposal } from './types.js';
import { EVOLUTION_CONFIG } from './config.js';
import { runSanityChecks } from './sanityChecker.js';

/**
 * Act: Execute the selected proposals
 * Note: This is a placeholder implementation.
 * In production, this would:
 * 1. Create a new branch
 * 2. Apply code changes
 * 3. Run lint/typecheck/tests
 * 4. Create a PR with the evolution template
 */
export async function act(proposals: EvolutionProposal[]): Promise<ActionResult[]> {
  const results: ActionResult[] = [];

  for (const proposal of proposals) {
    try {
      const result = await executeProposal(proposal);
      results.push(result);
    } catch (error) {
      results.push({
        success: false,
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  return results;
}

/**
 * Execute a single proposal
 */
async function executeProposal(proposal: EvolutionProposal): Promise<ActionResult> {
  // Generate branch name
  const today = new Date().toISOString().split('T')[0];
  const slug = proposal.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .substring(0, 30);
  const branchName = `${EVOLUTION_CONFIG.github.branch_prefix}${today}/${slug}`;

  // For this initial implementation, we'll return a dry-run result
  // In production, this would actually create branches, apply changes, run CI, and create PRs
  return {
    branch_name: branchName,
    success: true,
    pr_number: undefined,
    pr_url: undefined,
  };
}

/**
 * Create a GitHub PR with the evolution template
 */
export async function createEvolutionPR(
  branchName: string,
  proposal: EvolutionProposal
): Promise<{ pr_number: number; pr_url: string }> {
  // This would use the GitHub API to create a PR
  // For now, return mock data
  throw new Error('Not implemented - requires GitHub API integration');
}

/**
 * Generate PR body using the evolution template
 */
export function generatePRBody(proposal: EvolutionProposal): string {
  return `## Self-Evolution Proposal

**Type:** ${proposal.type}
**Risk Level:** ${proposal.risk_level}

### Description
${proposal.description}

### Expected Impact
${JSON.stringify(proposal.expected_impact || {}, null, 2)}

### Checklist
- [ ] Diff limited to allowlisted paths
- [ ] Lint/typecheck/tests/build passed
- [ ] Feature flags added with default safe values
- [ ] Rollback plan documented
- [ ] Risk level and expected impact stated
- [ ] Persona/appearance changes (if any) adhere to identity guardrails and are reversible

### Rollback Plan
1. Revert this PR immediately if issues are detected
2. Disable associated feature flags
3. Monitor error rates for 24h post-merge

### Safety Checks
All sanity checks passed before PR creation.

### Labels
${EVOLUTION_CONFIG.github.labels.map((label) => `\`${label}\``).join(', ')}

---
*This PR was generated by Omega's self-evolution system*
*Date: ${new Date().toISOString()}*
`;
}
